version: "3.8"

services:

  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:

      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: students_db

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "80:80"
    depends_on:
      - postgres

  students-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: students-service:latest
    container_name: students-service
    ports:
      - "8090:8090"
    depends_on:
      - postgres